// AUTO-GENERATED by scripts/generate-cloudflare-redirects.js — do not edit by hand.
// True 301 redirects for legacy + county paths, in a Cloudflare Pages Functions
// middleware. NOTE: production is currently served by GitHub Pages, which does NOT
// run this — it only takes effect if the custom domain is moved to the Cloudflare
// Pages deployment (works on the *.pages.dev preview). Exact-match, then falls
// through to assets.
const HOST = "https://thebeatboutique.ie";
const WWW_HOST = "www.thebeatboutique.ie";
const REDIRECTS = {
  "/playlist": "/song-list/",
  "/our-fans": "/reviews/",
  "/contact": "/showcase/",
  "/contact-us": "/showcase/",
  "/book": "/showcase/",
  "/book-us": "/showcase/",
  "/video": "/showcase/",
  "/videos": "/showcase/",
  "/showreel": "/showcase/",
  "/songlist": "/song-list/",
  "/songs": "/song-list/",
  "/pricing": "/pricing-guide/",
  "/prices": "/pricing-guide/",
  "/wedding-band-prices": "/pricing-guide/",
  "/testimonials": "/reviews/",
  "/why-us": "/about/",
  "/about1": "/about/",
  "/our-privacy-policy": "/privacy/",
  "/home": "/",
  "/get-in-touch": "/showcase/",
  "/watch-us-play": "/showcase/",
  "/evening-band": "/party-band/",
  "/whats-on-offer": "/pricing-guide/",
  "/the-seal-of-approval": "/reviews/",
  "/ceremony-music": "/song-list/",
  "/wedding-band-dublin": "/locations/wedding-band-dublin/",
  "/wedding-band-wicklow": "/locations/wedding-band-wicklow/",
  "/wedding-band-meath": "/locations/wedding-band-meath/",
  "/wedding-band-kildare": "/locations/wedding-band-kildare/",
  "/wedding-band-louth": "/locations/wedding-band-louth/",
  "/wedding-band-westmeath": "/locations/wedding-band-westmeath/",
  "/wedding-band-wexford": "/locations/wedding-band-wexford/",
  "/wedding-band-kilkenny": "/locations/wedding-band-kilkenny/",
  "/wedding-band-waterford": "/locations/wedding-band-waterford/",
  "/wedding-band-cork": "/locations/wedding-band-cork/",
  "/wedding-band-kerry": "/locations/wedding-band-kerry/",
  "/wedding-band-limerick": "/locations/wedding-band-limerick/",
  "/wedding-band-tipperary": "/locations/wedding-band-tipperary/",
  "/wedding-band-clare": "/locations/wedding-band-clare/",
  "/wedding-band-galway": "/locations/wedding-band-galway/",
  "/wedding-band-mayo": "/locations/wedding-band-mayo/",
  "/wedding-band-donegal": "/locations/wedding-band-donegal/"
};

export async function onRequest(context) {
  const url = new URL(context.request.url);
  let p = url.pathname;
  if (p.length > 1 && p.endsWith('/')) p = p.slice(0, -1);
  const target = REDIRECTS[p];
  // Legacy/county path redirect (single hop, always to apex) — covers apex AND www.
  if (target) {
    return new Response(null, { status: 301, headers: { Location: HOST + target + url.search } });
  }
  // www -> apex for everything else (canonical host), preserving path + query.
  // Non-GET/HEAD requests (e.g. a POSTed form submission from the www hostname)
  // must keep their method and body: a 301 would be converted to GET by the
  // browser and silently destroy the submission, so use 308 for those.
  if (url.hostname === WWW_HOST) {
    const method = context.request.method;
    const status = method === "GET" || method === "HEAD" ? 301 : 308;
    return new Response(null, { status, headers: { Location: HOST + url.pathname + url.search } });
  }
  return context.next();
}
